// seedServiceCodes.js
require("dotenv").config();
const mongoose = require("mongoose");
const ServiceCode = require("./model/IDB_SYS/Client/ServiceCode");

const seedData = [
  {
    Cost: 86.16,
    Description: "98960 Ed. and Training",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": 98906,
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 150,
    Description: "98960 HI T-C Behavior",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "HI",
    "Other EVV System": false,
    "Procedure Code": "98960 HI",
    "Short Desc": "98960 TC B",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 79.56,
    Description: "98960 TD T-C RN",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TD",
    "Other EVV System": false,
    "Procedure Code": 98960,
    "Short Desc": "T and C RN",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 34.56,
    Description: "99509 U6 BI Asst.Hab",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U6",
    "Other EVV System": false,
    "Procedure Code": 99509,
    "Short Desc": "AsstHab BI",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 150,
    Description: "Assesment - private",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": true,
    "Other EVV System": false,
    "Procedure Code": "RN pvt Assess",
    "Short Desc": "RN private",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 170,
    Description: "Assessment-LTCG",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": true,
    "Other EVV System": false,
    "Procedure Code": "LTCG RN",
    "Short Desc": "RN Assess",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 32,
    Description: "Assisted Trans-Zone I",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Kapuna",
    "Short Desc": "AT Zone 1",
    Status: "A",
    Type: "Other Charge",
  },
  {
    Cost: 38,
    Description: "Assisted Trans-Zone II",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "AT Zone 2",
    Status: "A",
    Type: "Other Charge",
  },
  {
    Cost: 0,
    Description: "Asst Trans. Hrs. Kupuna",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "AT-Kupuna",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 15,
    Description: "Attendant Care Zone 1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "AC Zone 1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 21,
    Description: "Attendant Care Zone 2",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "AC-Zone 2",
    "Short Desc": "AC Zone 2",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 16.5,
    Description: "Chore Worker Holiday",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 28,
    Description: "Chore Zone 1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Kapuna chore Z1",
    "Short Desc": "Chore Z1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 34,
    Description: "Chore Zone 2",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Kapuna Chore Z2",
    "Short Desc": "Chore Z 2",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 37,
    Description: "G0156 VA 2025",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "G0156",
    "Short Desc": "PA2 2025",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 31.64,
    Description: "H2021-U4 CLS Individual",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U4",
    "Other EVV System": false,
    "Procedure Code": "H2021",
    "Short Desc": "CLS Ind",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 24,
    Description: "Homemaker Kauai",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "HM Kauai",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0,
    Description: "Homemaker Zone I",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "HM Zone I",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 30,
    Description: "Homemaker Zone II",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "HM Zone II",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26,
    Description: "In-Home Respite Kau",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Contract#9768",
    "Short Desc": "Resp C9768",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 140,
    Description: "Medpour-PP",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": true,
    "Other EVV System": false,
    "Short Desc": "Medpour PP",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0.55,
    Description: "Mileage",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Mileage",
    "Short Desc": "Mileage",
    Status: "A",
    Type: "Other Charge",
  },
  {
    Cost: 0,
    Description: "Non-billable",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Non-billab",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0,
    Description: "Office hours - Non Bill",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Non billab",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0,
    Description: "Orientation - Non Bill",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Orient",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26,
    Description: "Personal Care Zone I",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "PC Zone I",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 32,
    Description: "Personal Care Zone II",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "PC Zone II",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 28,
    Description: "Personal Care-Kauai",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "PC-Kauai",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 39,
    Description: "PP Holiday 26",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "PP Holi 26",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 42,
    Description: "PP Holiday 28",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "PP Holi 28",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0,
    Description: "PP Holiday 29",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "PP holi 29",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 40,
    Description: "PP LPN 40",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "PP LPN 40",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 37.5,
    Description: "PP PA  25 OT",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26,
    Description: "PP PA  26",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 24,
    Description: "PP PA 24",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private pay",
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 25,
    Description: "PP PA 25",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private pay",
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 37.5,
    Description: "PP PA 25 Holiday Rate",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Pvt PA hol",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26,
    Description: "PP PA 26",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 27,
    Description: "PP PA 27",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 40.5,
    Description: "PP PA 27 OT",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Pvt PA OT",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 28,
    Description: "PP PA 28",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 42,
    Description: "PP PA 28 OT",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Pvt PA OT",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 29,
    Description: "PP PA 29",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 30,
    Description: "PP PA 30",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 32,
    Description: "PP PA 32",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 64,
    Description: "PP PA 32 Holiday 2X",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 35,
    Description: "PP PA 35",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Private PA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 52.5,
    Description: "PP PA 35 OT",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Pvt PA OT",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 45,
    Description: "PP PA 45",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "PP PA 45",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 65,
    Description: "PP PA 65",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Private RN",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 30,
    Description: "PP Respite 30",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay Respite",
    "Short Desc": "PP respite",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 110,
    Description: "PP RN 110",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private pay",
    "Short Desc": "Private110",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 140,
    Description: "PP RN 140",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": true,
    "Other EVV System": false,
    "Procedure Code": "Private pay",
    "Short Desc": "PP RN 140",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 52,
    Description: "PP RN 52",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private pay",
    "Short Desc": "Private RN",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 60,
    Description: "PP RN 60",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay",
    "Short Desc": "Private RN",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 70,
    Description: "PP RN 70",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Private Pay-RN",
    "Short Desc": "Private RN",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 75,
    Description: "PP RN 75",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "PP RN 75",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 350,
    Description: "Private-Live in",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "PP Live in",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0,
    Description: "Promotional Hours",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Promo",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0,
    Description: "Reports - Non Billable",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 24,
    Description: "Respite Care Z1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Kupuna RC Z1",
    "Short Desc": "RC Z1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26,
    Description: "Respite Care Z1 PC",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Respite Care Z1-PC",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 30,
    Description: "Respite Care Z2 HM",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Respite Care-Z2-HM",
    "Short Desc": "RC Z2 HM",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 32,
    Description: "Respite Care Z2 PC",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Kapuna RC Z2-PC",
    "Short Desc": "RC Z2 PC",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 24,
    Description: "Respite Care-Z1-HM",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Respite Care-Z1-HM",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 93.59,
    Description: "S5111 DD TC",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TD",
    "Other EVV System": false,
    "Procedure Code": "Training and Consulting",
    "Short Desc": "S5111 TC",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 89.68,
    Description: "S5116-TC",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5116-T and C -Behavior",
    "Short Desc": "S5116",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26.08,
    Description: "S5120-U1 Chore BI DD",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U1",
    "Other EVV System": false,
    "Short Desc": "ChoreBI DD",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 23.28,
    Description: "S5120-U2 Chore DD",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U2",
    "Other EVV System": false,
    "Short Desc": "Chore DD",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 30,
    Description: "S5125 AT HMSA",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5125",
    "Short Desc": "S5125 HMSA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 55,
    Description: "S5125 HMSA",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TD",
    "Other EVV System": false,
    "Procedure Code": "S5125",
    "Short Desc": "HMSA RN",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 66,
    Description: "S5125 TD HMSA 2020",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TD",
    "Other EVV System": false,
    "Procedure Code": "S5125",
    "Short Desc": "HMSA RN",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 17.6,
    Description: "S5125 U3 TX UHC HMKR",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U3",
    "Other EVV System": false,
    "Procedure Code": "S5125",
    "Short Desc": "S5125 U3",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 17.84,
    Description: "S5125 U3 U7 CFC UH HMKR",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U3",
    Mod2: "U7",
    "Other EVV System": false,
    "Procedure Code": "S5125",
    "Short Desc": "TX CFC HMK",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 64,
    Description: "S5125TD RN AlohaCare 20",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TD",
    "Other EVV System": false,
    "Procedure Code": "S5125",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 61.8,
    Description: "S5125-TD RN UHC",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TD",
    "Other EVV System": false,
    "Procedure Code": "S5125",
    "Short Desc": "RN 15mins",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 41.2,
    Description: "S5125-TE LPN UHC",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TE",
    "Other EVV System": false,
    "Procedure Code": "S5125",
    "Short Desc": "LPN 15mins",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 45,
    Description: "S5125TELPN AlohaCare 20",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TE",
    "Other EVV System": false,
    "Procedure Code": "S5125",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 29.84,
    Description: "S5125-U6-PAH 1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U6",
    "Other EVV System": false,
    "Procedure Code": "PA-Habilitation-Phasein",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 15,
    Description: "S5130 PA1 Alohacare",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5130",
    "Short Desc": "PA1 Aloha",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 24,
    Description: "S5130 PA1 HMSA",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5130",
    "Short Desc": "PA1 HMSA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 24,
    Description: "S5130 PA1 HMSA 2020",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5130",
    "Short Desc": "HMSA PA1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 18,
    Description: "S5130 PA1 Kaiser",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5130",
    "Short Desc": "PA1 Kaiser",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 20,
    Description: "S5130 PA1 Ohana 2019",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5130",
    "Short Desc": "PA1 Ohana",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 19.32,
    Description: "S5130 PA1 UHC 102018",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5130",
    "Short Desc": "S5130 PA1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 19,
    Description: "S5130PA1 Alohacare 202",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5130",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 15,
    Description: "S5135-Alohacare",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5135",
    "Short Desc": "Comp Aloha",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 20.6,
    Description: "S5150 Respite",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5150",
    "Short Desc": "Respite",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 22.6,
    Description: "S5150 Respite DD 1.1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S5150 Respite",
    "Short Desc": "Respite DD",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 23,
    Description: "S9122 PA2 AlohaCare",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9122",
    "Short Desc": "PA2 Aloha",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 30,
    Description: "S9122 PA2 HMSA",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9122",
    "Short Desc": "PA2 HMSA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 30,
    Description: "S9122 PA2 HMSA 2020",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9122",
    "Short Desc": "HMSA PA2",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 23.69,
    Description: "S9122 PA2 Kaiser",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9122",
    "Short Desc": "PA2 Kaiser",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 23,
    Description: "S9122 PA2 Ohana",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9122",
    "Short Desc": "PA2 Ohana",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 25,
    Description: "S9122 PA2 Ohana 2019",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9122",
    "Short Desc": "PA2 Ohana",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 23.69,
    Description: "S9122 PA2 UHC",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9122",
    "Short Desc": "PA2 UHC",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 24,
    Description: "S9122PA2 Alohacare 2020",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9122",
    "Short Desc": "S9122 PA2",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26.12,
    Description: "S9122-VA-Home Health",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9122",
    "Short Desc": "HHA VA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 66,
    Description: "S9123 RN HMSA",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9123",
    "Short Desc": "RN HMSA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 66,
    Description: "S9123 RN HMSA 2020",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9123",
    "Short Desc": "RN HMSA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 55.62,
    Description: "S9123 RN Kaiser",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9123",
    "Short Desc": "RN Kaiser",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 57.62,
    Description: "S9123 RN Maui Kaiser",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9123",
    "Short Desc": "RN Mau Kai",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 60,
    Description: "S9123 RN Ohana 2019",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9123",
    "Short Desc": "RN Ohana",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 55.62,
    Description: "S9123 RN UHC",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9123",
    "Short Desc": "RN UHC",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 58,
    Description: "S9123RN Alohacare 2020",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9123",
    "Short Desc": "RN Aloha20",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 51,
    Description: "S9124 LPN HMSA",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9124",
    "Short Desc": "Lpn HMSA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 42.5,
    Description: "S9124 LPN Kaiser",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9124",
    "Short Desc": "LPN Kaiser",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 42.5,
    Description: "S9124 LPN Ohana 2019",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9124",
    "Short Desc": "LPN Ohana",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 38.98,
    Description: "S9124 LPN UHC",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9124",
    "Short Desc": "LPN UHC",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26.12,
    Description: "S9125 Respite VA",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "S9125",
    "Short Desc": "Respite VA",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0,
    Description: "Show up Fees - non bill",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "Show up",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0,
    Description: "Staff  Mtgs-nonbillable",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Staff  Mtgs-nonbillable",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 79.4,
    Description: "T1000-U5 DD Prvt Duty",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "T1000",
    "Short Desc": "Prvt Duty",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 101.48,
    Description: "T1002 RN BI DD",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "RN BI DD",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 86.52,
    Description: "T1002-TD RN DD",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TD",
    "Other EVV System": false,
    "Short Desc": "RN DD",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 62.08,
    Description: "T1003 LPN DD",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Short Desc": "LPN DD",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 50.72,
    Description: "T1003-TE LPN BI DD",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "TE",
    "Other EVV System": false,
    "Short Desc": "LPN BI DD",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 18,
    Description: "T1005 Repsite DD",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "T1005",
    "Short Desc": "DD Respite",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 14.24,
    Description: "T1005 U3 TX UHC Respite",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U3",
    "Other EVV System": false,
    "Procedure Code": "T1005",
    "Short Desc": "T1005 U3",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 142.6,
    Description: "T1005-22 respite daily",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": true,
    Mod1: 22,
    "Other EVV System": false,
    "Procedure Code": "T1005",
    "Short Desc": "DD Daily",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 23.36,
    Description: "T1005-U1 Respite BI DD",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U1",
    "Other EVV System": false,
    "Short Desc": "Resp-BI DD",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26.16,
    Description: "T1019-U6 PAB1 1.1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U6",
    "Other EVV System": false,
    "Procedure Code": "T1019",
    "Short Desc": "DDPAB1 1:1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 26.16,
    Description: "T1019-U7 PAB1 2.1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U7",
    "Other EVV System": false,
    "Procedure Code": "T1019",
    "Short Desc": "DDPAB1 2:1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 29,
    Description: "T1019-UA PAB2 1.1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "UA",
    "Other EVV System": false,
    "Procedure Code": "T1019",
    "Short Desc": "DDPAB2 1:1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 29,
    Description: "T1019-UB PAB2 2.1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "UB",
    "Other EVV System": false,
    "Procedure Code": "T1019",
    "Short Desc": "DDPAB2 2:1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 87,
    Description: "T1019-UC PAB2 3.1",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "UC",
    "Other EVV System": false,
    "Procedure Code": "T1019",
    "Short Desc": "DDPAB2 3:1",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 38,
    Description: "T2021 U4 CLS BI Ind",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    Mod1: "U4",
    "Other EVV System": false,
    "Procedure Code": "Comm. Learning Big Island",
    "Short Desc": "CLS BI Ind",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 0,
    Description: "Training - non billable",
    "E\/D": " ",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    "Procedure Code": "Training",
    "Short Desc": "Training",
    Status: "A",
    Type: "Service",
  },
  {
    Cost: 7.25,
    Description: "Travel Time",
    "E\/D": "S",
    "Enable CDC": false,
    "Flat Rate Per Shift": false,
    "Other EVV System": false,
    Status: "A",
    Type: "Service",
  },
  // ... Add all other objects from your JSON
];

const mapToServiceCodeSchema = (data) => {
  const status = data.Status === "A" ? "Active" : "Inactive";
  const billedPerVisit =
    data["Flat Rate Per Shift"] === true ? "Flat Rate" : "Hourly";
  let type = "Service";
  if (data.Type === "Mileage") type = "Mileage";
  // If you have "Other Charge" in your enum, add it here

  return {
    description: data.Description || "",
    shortDesc: data["Short Desc"] || "",
    procedureCode: data["Procedure Code"] ? String(data["Procedure Code"]) : "",
    type: type,
    cost: data.Cost || 0,
    status: status,
    billedPerVisit: billedPerVisit,
    adpIncludeInAdjustedDed: false,
    overridePaychexFlex: false,
    payplusExport: {
      regularCode: "",
      overtimeCode: "",
      holidayCode: "",
      type: type,
    },
    mod1: data.Mod1 || "",
    mod2: data.Mod2 || "",
    mod3: data.Mod3 || "",
    mod4: data.Mod4 || "",
    tos: "",
    supplementalInfo: "",
    revCode: "",
    otherEVVSystem: data["Other EVV System"] || false,
    taxonomyCode: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  };
};

// Main seed function
const seedServiceCodes = async () => {
  try {
    console.log("Starting service code seed...");

    // Connect to MongoDB directly
    const mongoUrl = process.env.MONGO_DB_URL;
    if (!mongoUrl) {
      throw new Error("MONGO_DB_URL environment variable is not set");
    }

    await mongoose.connect(mongoUrl, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("✅ Database connected successfully");

    // Clear existing service codes (optional)
    const clearExisting = process.argv.includes("--keep") ? false : true;
    if (clearExisting) {
      const deleteResult = await ServiceCode.deleteMany({});
      console.log(
        `🗑️  Cleared ${deleteResult.deletedCount} existing service codes`,
      );
    }

    // Map and insert seed data
    const serviceCodes = seedData.map(mapToServiceCodeSchema);
    const result = await ServiceCode.insertMany(serviceCodes);

    console.log(`✅ Successfully seeded ${result.length} service codes`);

    // Verification
    console.log("\n📊 Summary Statistics:");

    // Get counts by status
    const statusCounts = await ServiceCode.aggregate([
      { $group: { _id: "$status", count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]);

    console.log("\n📈 Status Breakdown:");
    statusCounts.forEach((item) => {
      console.log(`  ${item._id}: ${item.count}`);
    });

    // Get counts by billedPerVisit
    const billingCounts = await ServiceCode.aggregate([
      { $group: { _id: "$billedPerVisit", count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]);

    console.log("\n💰 Billing Type Breakdown:");
    billingCounts.forEach((item) => {
      console.log(`  ${item._id}: ${item.count}`);
    });

    // Get counts by type
    const typeCounts = await ServiceCode.aggregate([
      { $group: { _id: "$type", count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]);

    console.log("\n🏷️  Type Breakdown:");
    typeCounts.forEach((item) => {
      console.log(`  ${item._id}: ${item.count}`);
    });

    // Show a few sample records
    console.log("\n📋 Sample Records (first 3):");
    const samples = await ServiceCode.find({})
      .sort({ createdAt: -1 })
      .limit(3)
      .select("description cost status billedPerVisit type");

    samples.forEach((doc, index) => {
      console.log(`\n  ${index + 1}. ${doc.description}`);
      console.log(`     Cost: $${doc.cost}, Status: ${doc.status}`);
      console.log(`     Billed: ${doc.billedPerVisit}, Type: ${doc.type}`);
    });

    // Close connection
    await mongoose.disconnect();
    console.log("\n🔌 Database connection closed");
  } catch (error) {
    console.error("❌ Error seeding service codes:", error.message);
    if (error.code === 8000) {
      console.error("Authentication failed. Check your MongoDB credentials.");
    }
    process.exit(1);
  }
};

// Run with optional flags
if (process.argv.includes("--help") || process.argv.includes("-h")) {
  console.log(`
Usage: node seedServiceCodes.js [options]

Options:
  --keep      Keep existing records (don't clear before seeding)
  --help, -h  Show this help message

Example:
  node seedServiceCodes.js          # Clear and seed
  node seedServiceCodes.js --keep   # Add to existing records
  `);
  process.exit(0);
}

// Run the seed
seedServiceCodes();
